custom_rules:
  equal_space:
    name: "Spacing Violation."
    regex: "=[ ]{2,}"
    message: "There should be only one whitespace after equal"
    severity: warning
disabled_rules:
  - cyclomatic_complexity
  - line_length
  - implicit_getter
  - todo
  - trailing_whitespace
  - large_tuple
  - fallthrough
  - multiple_closures_with_trailing_closure
opt_in_rules: 
  - empty_count
  - force_unwrapping

included: # paths to include during linting. `--path` is ignored if present.
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests
  
   # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error # implicitly
force_try:
  severity: error # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
#line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
function_parameter_count:
  warning: 7
  error: 10
file_length:
  warning: 800
  error: 1200
function_body_length:
  warning: 90
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
nesting:
  type_level: 3
identifier_name:
  allowed_symbols: "_"
  min_length: 1
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id
    - URL
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)
